### PR TITLE
Readme update / Installer

### LINKED ISSUE #70: better readme and doc
the readme and the documentation need some improvements

some of the information on the readme should be moved to the documentation to avoid maintaining stuff on two places

in particular the quick start should be a real quick start without sources compilation, we need a docker image and/or an auto install script you can fetch with curl

### PR DESCRIPTION
**Pull request by banditopazzo**
# Readme update / Installer

- Readme revision
- Introduce the install script
- Change few doc sections in the source code
- Fix doc broken links (some structures need to be public to be linked in the doc, but fields and constructors remain private)

Closes #70

## I have 

- [x] run `cargo fmt`;
- [x] run `cargo clippy`;
- [x] run `cargo test`and all tests pass;
- [x] linked to the originating issue (if applicable).

### CODE REVIEW

**Review by krsh — APPROVED** [review]

**Comment by MatteoNardi** [comment]
Many links end in a page not found.

I like the changes, it does a great job at showing what's the point of pulsar and how to use it. Kudos

We've removed some developer focused info. I think these would be a better fit for a different README on this github repo, but even if we decide to move them to the main documentation website, we should make sure not to loose these:
- Running the test suite (this should be done by users too)
- xtasks
- single probe runner
- Why we require a given kernel version (eg. replacing what features would allow us to support an older one)
- Why we require a given kernel config

**Comment by hnidoaht-101** [comment]
Also, just a suggestion, while running test suite, I noticed [this note](https://github.com/Exein-io/pulsar/blob/main/bpf-common/src/feature_autodetect/lsm.rs#L3-L7). It was failed because my system didn't have `bpf` to be listed in `/sys/kernel/security/lsm`.
Therefore, I did a search and I found [the guidance](https://aya-rs.dev/book/programs/lsm/#ensure-that-bpf-lsm-is-enabled) in aya docs to manually enable it.
I recommend we should put the link in [this README.md](https://github.com/Exein-io/pulsar/blob/main/bpf-common/README.md) also with a note for LSM feature-autodetection.

**Comment by banditopazzo** [comment]
@MatteoNardi ok for broken links

developers commands are in the official doc in [developers](https://pulsar.sh/docs/category/developers) section. I will add another link to have it more explicit

also the details for the kernel are in the [Kernel Requirements](https://pulsar.sh/docs/faq/kernel-requirements) section

**Comment by banditopazzo** [comment]
@hnidoaht-101 you are right, I will find a place to add this in the documentation thanks

**Pull request merged**
